FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive
ENV SHELL /bin/bash
ENV GIT_EDITOR=nano
RUN apt update \
  && apt install -y zlib1g-dev libsqlite3-dev libffi-dev libpq-dev libyaml-dev nodejs ruby-full npm curl sudo \
     supervisor zsh git nano python3 python3-pip python3.12-venv python3-django \
  && curl -o- -L https://yarnpkg.com/install.sh | bash \
  && export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" \
  && curl -fsSL https://code-server.dev/install.sh | sh \
  && mkdir -p /var/log/supervisor

# Add student user as uid 1000
RUN deluser ubuntu \
  && useradd -m -u 1000 -s /bin/bash student \
  && passwd -d student \
  && usermod -aG sudo student \
  && chown -R student:student /var/log/supervisor 

ADD supervisord.conf /etc/

USER student

EXPOSE 80 3000

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
